/* eslint-disable @next/next/no-img-element */
import '../../public/styles/globals.scss'
import Header from '@/layout/template/Header'
import { Inter } from 'next/font/google'
import { storage } from '@/config/firebaseConfig'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const mei = await storage.ref('images/mei.png').getDownloadURL();
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="block relative w-full h-full overflow-hidden bg-gradient-to-br from-gray-950 from-30% via-purple-500 via-50% to-pink-500 to-90%">
      <Header></Header>
      <img 
        src={mei} 
        alt="mei"
        className="absolute bottom-0 top-24"/>
      <div className="fixed flex top-0 right-0 bottom-0 max-w-md w-full bg-gradient-to-r from-cyan-500 to-blue-500">
        {children}
      </div>
      </div>
      </body>
    </html>
  )
}
